### ISSUE TITLE
Procurar como fazer validação de schema em JSON

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/insiderNews#129]

**Comment by filipedeschamps** [comment]
* https://www.npmjs.com/package/jsonschema
* https://github.com/apiaryio/Amanda
* https://github.com/hapijs/joi
* https://github.com/geraintluff/tv4
* https://github.com/zaggino/z-schema
* https://www.npmjs.com/package/async-validate

É bom também olhar este documento do Google sobre padronização de JSON, principalmente na parte dos erros:
* https://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml

**Comment by filipedeschamps** [comment]
Depois de muito estudar e pesquisar, fiquei ente estes dois:

* https://www.npmjs.com/package/jsonschema (44 mil downloads por mês)
* https://www.npmjs.com/package/tv4 (109 mil downloads por mês)

<h2>Pontos bons do jsonschema:</h2>

* Ele suporta de forma nativa a propriedade `format`, onde o tv4 você precisa colocar como plugin ou apelar para regex.
* Apesar do `tv4` ter o dobro de popularidade, ele tem o quadruplo de issues e menos pull requests que o `jsonschema`.

<h2>Pontos bons do tv4:</h2>
* Ele é o dobro popular e possui um ciclo de release maior (27 contra 19 do jsonschema) e foi atualizado faz 20 dias contra 7 meses do jsonschema.
* A API que ele expõe parece ser mais amigável
* Ele retorna error code, e não somente string.

<h2>Ganhador</h2>
Por hora, vou começar os testes pelo `tv4` e vou ver até onde consigo chegar. Se ele falhar, tento como plano b o `jsonschema`

/cc @airroom

**Comment by filipedeschamps** [comment]
E para ajudar, tem uma ferramenta muito legal que gera o schema para você a partir de um dado de exemplo: http://jsonschema.net/

É bom para estudar.

**Comment by FabricioFFC** [comment]
@filipedeschamps boa análise. Os dois me parecem boas opções.

Uma coisa interessante pra levar em conta é que o tv4 tem mais projetos que dependem dele: https://www.npmjs.com/browse/depended/tv4 contra https://www.npmjs.com/browse/depended/jsonschema

**Comment by airroom** [comment]
@FabricioFFC, nem sabia que dava para ver isso. Valeu!

**Comment by filipedeschamps** [comment]
@FabricioFFC caramba que legal isso, também não conhecia!

**Comment by filipedeschamps** [comment]
Ontem fiz uma implementação rápida com ele https://github.com/filipedeschamps/insiderNews/pull/161/files

Estou matutando aqui como posso fazer para customizar as mensagens de erro e expor isto de uma forma super fácil de dar bind.

Por exemplo salvar dentro do estado da instância se ele está com erros, mesmo princípio do data que eu exponho e faço bind direto no viewModel.

**controller.js**
``` javascript
vm.news = createNews(...);
vm.news.errors; // undefined
vm.news.validate(); // valida o schema e guarda os erros dentro da instância
vm.news.errors; // [...]
```

**view.html**
```html
<!-- para apontar de forma manual onde mostrar o erro -->
<div class="error-message" ng-show="vm.news.errors['title']">
   {{ vm.news.errors['title'] }}
</div>

<!-- ou ng-repeat para listar geral -->
<div class="error-message" ng-repeat="error in vm.news.errors">
   {{error.description}}
</div>
```

O que acham?

**Comment by filipedeschamps** [comment]
Funcionou perfeitamente expor o objeto `errors` e mostrar na view quando tiver alguma informação populada nele. E o bom é que segue exatamente o mesmo princípio de export o `data`.

O que me deu uma rasteira foi estes dois validadores. A validação contra o schema é perfeita, você pula de um módulo para o outro de forma transparente, pois é tudo o mesmo padrão. Agora, o que ficou longe de ter um padrão é como as mensagens de erro são devolvidas do validador. Cada um retorna de uma forma mais estranha que o outro em casos de validação como de quantidade de caracteres mínimos.

Para nenhum dos dois validadores eu consegui bolar um formatador que consiga cobrir as variações que quero para sempre sair do model o mesmo formato de erro, é incrível. Mas nessas horas ter várias alternativas no ecosistema ajuda, encontrei um validador de schema que é o mais veloz de todos hoje e traz mensagens de erro muito simples: https://www.npmjs.com/package/is-my-json-valid

Para testar na view fiz a implementação manual com `ng-if`para mostrar/esconder a mensagem e também colocar uma classe no input, ficou muito simples:

![image](https://cloud.githubusercontent.com/assets/4248081/6217761/77c6c17e-b5fe-11e4-9dc5-0462526864d9.png)

![image](https://cloud.githubusercontent.com/assets/4248081/6217775/a7d590ac-b5fe-11e4-9c65-af938fb6203c.png)
